# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Simple Pipe

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  # ability to run manually
  workflow_dispatch:
    inputs:
      myVersion:
        description: 'Input Version'
      myValues:
        description: 'Input Values'
        
permissions:
  contents: read

jobs:
  # build is the first job
  build:
    runs-on: ubuntu-latest

    # Map a step output to a job output (jarpath at line 66)
    # steps (setoutput is the id for the output step, jarpath is the new env variable name)
    # artifact-path is the variable value that is used to reference the value from the second job
    outputs:
      artifact-path: ${{ steps.setoutput.outputs.jarpath }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build

    # use env context to set and retrieve values from $GITHUB_ENV temp file
    - name: Set timestamp
      run: echo TDS=$(date +'%Y-%m-%dT%H-%M-%S') >> $GITHUB_ENV 

    # retrieve value from env context
    - name: Tag artifact
      run: mv build/libs/greetings-add.jar build/libs/greetings-add-${{ github.event.inputs.myVersion}}${{ env.TDS }}.jar
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: greetings-jar
        path: |
            build/libs
            test-script.sh

    # output value for this job - notice id value
    # this set the job up to return the artifact name
    - name: Set output
      id: setoutput
      run: echo jarpath=build/libs/greetings-add-${{ github.event.inputs.myVersion}}${{ env.TDS }}.jar >> $GITHUB_OUTPUT

  # print-build-output is the 2nd job
  # needs parameter references the first job name
  print-build-output:
   runs-on: ubuntu-latest
   needs: build
   steps:
   - run: echo ${{needs.build.outputs.artifact-path}}

  # new job - test runner
  # it executes a bash script that it copies into the runner (vm) from the root of the repo
  # coping the file required the edit to the upload path in the build job - the pipe (|) is significant
  test-run:
   runs-on: ubuntu-latest
   needs: build
  
   steps:
   - name: Download candidate artifacts
     uses: actions/download-artifact@v3
     with:
       name: greetings-jar
  
   - name: Execute test
     shell: bash
     run: |
       chmod +x ./test-script.sh
       ./test-script.sh ${{ needs.build.outputs.artifact-path }} ${{ github.event.inputs.myValues }}

  # lab 6
  # run a custom workflow from another repo
  # first run will throw an error becauses uses is set to an invalid github username
  count-args:
   runs-on: ubuntu-latest
  
   steps:
     - id: report-count
       uses: rcatalanolp/arg-count-action@main
       with:
         arguments-to-count: ${{ github.event.inputs.myValues }}
     - run: echo
     - shell: bash
       run: |
           echo argument count is ${{ steps.report-count.outputs.arg-count }} 
